### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by kurousa000** [huntvee/mia-n-vg#1]
hi im hun\ ng

**Comment by huntvee** [comment]
Ho

**Comment by kurousa000** [comment]
That’s it…. I’M DELETING YOU, DADDY!😭👋
██]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]] 10% complete.....
████]]]]]]]]]]]]]]]]]]]]]]]]]]] 35% complete....
███████]]]]]]]]]]]]]]]] 60% complete....
███████████] 99% complete.....
🚫ERROR!🚫 💯True💯 Daddies are irreplaceable 💖I could never delete you Daddy!💖 Send this to ten other 👪Daddies👪 who give you 💦cummies💦 Or never get called ☁️squishy☁️ again❌❌😬😬❌❌ If you get 0 Back: no cummies for you 🚫🚫👿 3 back: you’re squishy☁️💦 5 back: you’re daddy’s kitten😽👼💦 10+ back: Daddy
m — 09/08/2023 20:43
Just me and my 💕daddy💕, hanging out I got pretty hungry🍆 so I started to pout 😞 He asked if I was down ⬇for something yummy 😍🍆 and I asked what and he said he'd give me his 💦cummies!💦 Yeah! Yeah!💕💦 I drink them!💦 I slurp them!💦 I swallow them whole💦 😍 It makes 💘daddy💘 😊happy😊 so it's my only goal... 💕💦😫H
